controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint1_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint2_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint3_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint4_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

joint1_trajectory_controller:
  ros__parameters:
    joints:
      - joint1

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

joint2_trajectory_controller:
  ros__parameters:
    joints:
      - joint2

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

joint3_trajectory_controller:
  ros__parameters:
    joints:
      - joint3

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

joint4_trajectory_controller:
  ros__parameters:
    joints:
      - joint4

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true